### PR TITLE
Document the assumed unit of angles

### PR DESCRIPTION
**Pull request by HannesSommer**

### CODE REVIEW

**Comment by HannesSommer** [comment]
Can someone confirm that kindr::minimal::AngleAxis uses radians as units everywhere? This is Eigen's documentation https://eigen.tuxfamily.org/dox/classEigen_1_1AngleAxis.html.

**Comment by helenol** [comment]
add to whitelist

**Comment by helenol** [comment]
LGTM

**Comment by HannesSommer** [comment]
Thanks!

**Pull request merged**
