### PR TITLE
Added dependencies.rosinstall file

### PR DESCRIPTION
**Pull request by HannesSommer**

### CODE REVIEW

**Comment by ntonci** [comment]
@HannesSommer it seems that this PR breaks build on jenkins for voxblox_gsm (I assume also voxblox). Is it possible to make these ssh instead of https:
```
Processing dependency file minkindr/dependencies.rosinstall
ERROR : minkindr/dependencies.rosinstall : catkin_simple(https://github.com/catkin/catkin_simple.git, None) differs from former .rosinstall : catkin_simple(git@github.com:catkin/catkin_simple.git, None) (different versions / URIs for the same local-name are not supported)
ERROR : minkindr/dependencies.rosinstall : gflags_catkin(https://github.com/ethz-asl/gflags_catkin, None) differs from former .rosinstall : gflags_catkin(git@github.com:ethz-asl/gflags_catkin.git, None) (different versions / URIs for the same local-name are not supported)
ERROR : minkindr/dependencies.rosinstall : glog_catkin(https://github.com/ethz-asl/glog_catkin, None) differs from former .rosinstall : glog_catkin(git@github.com:ethz-asl/glog_catkin.git, None) (different versions / URIs for the same local-name are not supported)
ERROR : minkindr/dependencies.rosinstall : eigen_catkin(https://github.com/ethz-asl/eigen_catkin.git, None) differs from former .rosinstall : eigen_catkin(git@github.com:ethz-asl/eigen_catkin.git, None) (different versions / URIs for the same local-name are not supported)
ERROR : minkindr/dependencies.rosinstall : eigen_checks(https://github.com/ethz-asl/eigen_checks.git, None) differs from former .rosinstall : eigen_checks(git@github.com:ethz-asl/eigen_checks.git, None) (different versions / URIs for the same local-name are not supported)
```

**Comment by HannesSommer** [comment]
Oh my. Thanks for reporting. Now we can start the blame game :). IMO we should not depend on ssh uris unless it is private repos. The reason is that one needs a github account and ssh-key registered to pull from those. Hence, I would suggest that we change voxblox. Who is currently maintaining it?

**Comment by HannesSommer** [comment]
Another way is to to convert the ERRORS into warnings. I'll try that quickly.

**Comment by ntonci** [comment]
It's actually voxblox_gsm only, voxblox has manually set dependencies in the jenkins config. 
I guess this is fine, @ffurrer will try to fix the jenkins script such that this error does not appear if you have both (just to take the ssh one).

**Comment by HannesSommer** [comment]
On, @ffurrer , I already started this fix. But not with any preference. The first seen is checked out already at the time of collision (possibly).

**Comment by HannesSommer** [comment]
@ntonci , @ffurrer could you retry the voxblox_gsm, now that #117 is merged?

**Comment by ntonci** [comment]
@HannesSommer yes, this resolves the issue on voxblox_gsm. Thanks for the fix!

**Pull request merged**
