### PR TITLE
QtCreator compatibility: Headers in CMakeLists.txt

### PR DESCRIPTION
**Pull request by cfo**
Using QtCreator requires that we add all header files to the CMakeLists.txt as the CMakeListst.txt is QtCreator's main project file.

### CODE REVIEW

**Comment by simonlynen** [comment]
Lgtm.

**Comment by simonlynen** [comment]
add to whitelist

**Comment by cfo** [comment]
what do you mean by "add to whitelist"?
by the way, i don't have the rights to merge.

**Comment by simonlynen** [comment]
@cfo "add to whitelist" is a command to the CI server to automatically build your PRs from now on.

**Comment by simonlynen** [comment]
@cfo you should have write access, but probably just if you directly clone the repo.

**Pull request merged**
