### PR TITLE
Feature/gtsam bad

### PR DESCRIPTION
**Pull request by furgalep**
@mikebosse, take a look at this. I'm making progress.

### CODE REVIEW

**Comment by gawela** [comment]
@furgalep  @mikebosse we refactored minkindr_gtsam for the latest gtsam/develop branch.

**Comment by furgalep** [comment]
Any way to make the build build on the build server.

build.

**Comment by simonlynen** [comment]
letting minkindr depend on gtsam seems like a bad idea.

https://en.wikipedia.org/wiki/Gordian_Knot

**Comment by gawela** [comment]
@furgalep jenkins needs updates on gtsam_related packages. Who can give me access?
@simonlynen minkindr_gtsam lives in parralel to minkindr to glue it with gtsam traits & expressions.

**Comment by furgalep** [comment]
@simonlynen, we can move the minkindr_gtsam stuff to another repo if that works better.

I agree that minkindr is pretty fundamental.

**Comment by simonlynen** [comment]
@furgalep in general this is fine if it doesn't make minkindr itself depend on gtsam. We will need to add gtsam to the build-deps on jenkins.

At least this will (hopefully) lead to people not building the entire workspace all the time.

**Comment by simonlynen** [comment]
Also you need to merge master into this and resolve the conflicts.

**Comment by furgalep** [comment]
test this please

**Comment by furgalep** [comment]
test this please

**Comment by furgalep** [comment]
test this please

**Comment by furgalep** [comment]
@rdube, is it possible that the curves version of gtsam is not up to date?

http://129.132.38.183:8080/job/minkindr/62/label=osx/console

**Comment by HannesSommer** [comment]
The gtsam master on our data server, which it uses, is : 
```
d7bf997: Merged in feature/matlabVectorsAndMatrices (pull request #50)
```
So probably outdated.

**Comment by furgalep** [comment]
Hi @HannesSommer! How can I fix that?

**Comment by rdube** [comment]
I updated gtsam master on our data server  to commit ff61d92283b371f88a7a594d1a0ec756b8675cc2 revision of december 30th which we are using for development on our local machines. 

I have launched a build on jenkins. Let's see..

**Comment by furgalep** [comment]
test this please

**Comment by furgalep** [comment]
test this please

**Comment by furgalep** [comment]
The OSX build fails with this:

```
/Users/slynen/workspace/minkindr/label/osx/devel/include/gtsam/base/Manifold.h:84:28: error: non-type template argument evaluates to -1, which cannot be narrowed to type 'size_t' (aka 'unsigned long') [-Wc++11-narrowing]
struct ManifoldImpl<Class, Eigen::Dynamic>
```

I have a fix for this working its way through the gtsam review process. I say we just pull this as is. It compiles fine on Ubuntu. OSX GTSAM users can check out the `fix/c++11-narrowing` branch.

**Comment by furgalep** [comment]
Broke Jenkins...Creating a new PR.

**Pull request closed without merging**
